create table curators (
/*id integer primary key generated by default as identity,*/
id serial primary key,
name varchar(255) not null check (name <> ''), -- unique не применяется, так как пусть один и тот же куратор может быть у разных групп
groupe_number integer not null unique
);

commit;

create table students (
id integer primary key generated by default as identity,
name varchar(255) not null check (name <> ''),
groupe_number integer not null, /*references curators (groupe_number) on delete set default,*/
foreign key (groupe_number) references curators(id) on delete set default
);

commit;

-- Заполнение таблицы "Кураторы"
-- Пусть групп будет 3 шт (№1, №2, №3)
-- Первое поле заполняется автоматически
insert into curators (id, name, groupe_number) 
		values
(default, 'Куратор_1', 1),
(default, 'Куратор_2', 2),
(default, 'Куратор_3', 3);

commit;

-- Заполнение таблицы "Студенты"
-- Пусть групп будет 3 шт (№1, №2, №3)
-- Первое поле заполняется автоматически
insert into students (id, name, groupe_number) 
		values
(default, 'Студент_1', 1),
(default, 'Студент_2', 1),
(default, 'Студент_3', 2),
(default, 'Студент_4', 3),
(default, 'Студент_5', 3),
(default, 'Студент_6', 3),
(default, 'Студент_7', 2),
(default, 'Студент_8', 2),
(default, 'Студент_9', 1),
(default, 'Студент_10', 3);

commit;

select * from students;
select * from curators;

-- Вывод на экран списка студентов с указанием куратора группы,
-- в которой данный студент. Отсортировать по по номеру группы
select t1.*, t2.name as "Куратор"  from students as t1
left join curators as t2 on t1.groupe_number = t2.groupe_number
order by t2.groupe_number, t1.id

-- (Дополнительное условие к заданию)
-- Пусть возникла необходимость создания ещё одной группы №4, но куратора отдельного нет
-- и группу №4 пусть будет курировать Куратор_2

-- Добавление новой группы №4. но куратор в ней бет тот же что и в группе №2
insert into curators (id, name, groupe_number) 
		values
(default, 'Куратор_2', 4);	--Куратор_2 теперь курирует две группы

commit;

-- Перевод Студента_3 и Студента_6 в группу №4
update students set groupe_number = 4
		where id in (select t2.id from students as t2 where (t2.name like 'Студент_3' or t2.name like 'Студент_6'));

commit;

-- Вывод на экран списка студентов с указанием куратора группы,
-- в которой данный студент. Отсортировать по номеру группы
select t1.*, t2.name as "Куратор"  from students as t1
left join curators as t2 on t1.groupe_number = t2.groupe_number
order by t2.groupe_number, t1.id

-- Вывод на экран списка кураторов, которые курируют 3-х и более студентов  (не зависимо от вхождения в группы)
-- Отсортировать по номеру группы
select t1."name" as "Студент", t2.name as "Куратор", t1.groupe_number as "Номер группы"  from students as t1
left join curators as t2 on t1.groupe_number = t2.groupe_number
where (select count(*) from students as t3 where t3.groupe_number in (select t4. groupe_number from curators as t4 where t4.groupe_number = t1.groupe_number)) >= 3
group by t2.name, t1.groupe_number, t1."name";

-- Удалить студента 'Студент_3'
delete from students where id = (select t2.id from students as t2 where (t2.name like 'Студент_3')); 
--drop table students;
--drop table curators;
